### ISSUE TITLE
Undeclared hard dependencies

### ISSUE THREAD

**Issue by mikeraimondi** [bensaufley/gnurr#1]
The project has at least two undeclared, hard dependencies: `git` and `perl` must be in the user's $PATH. At a minimum, they should be declared in all relevant documentation. Even better, eliminate them by using an alternative API such as [ruby-git](https://github.com/schacon/ruby-git).

**Comment by bensaufley** [comment]
Thanks. Ruby-git is what I've been looking for!!! Or, maybe. Rather than using perl and RegExes – it looks like I might be able to use that to (hopefully) more programmatically parse the diff.
